// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorConfig } from "./EditorConfig";
import type { EnvironmentInfo } from "./EnvironmentInfo";
import type { ExecutorConfig } from "./ExecutorConfig";
import type { GitHubConfig } from "./GitHubConfig";
import type { SoundFile } from "./SoundFile";
import type { ThemeMode } from "./ThemeMode";

export type Config = { theme: ThemeMode, executor: ExecutorConfig, disclaimer_acknowledged: boolean, onboarding_acknowledged: boolean, github_login_acknowledged: boolean, telemetry_acknowledged: boolean, sound_alerts: boolean, sound_file: SoundFile, push_notifications: boolean, editor: EditorConfig, github: GitHubConfig, analytics_enabled: boolean | null, environment: EnvironmentInfo, workspace_dir: string | null, };
