// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorConstants } from "./EditorConstants";
import type { Environment } from "./Environment";
import type { SoundConstants } from "./SoundConstants";

export type ConfigConstants = { editor: EditorConstants, sound: SoundConstants, mode: Environment, };
