// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateTask = { project_id: string, title: string, description: string | null, parent_task_attempt: string | null, };
