// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateTaskAttempt = { executor: string | null, base_branch: string | null, };
