// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateExecutorSession = { task_attempt_id: string, execution_process_id: string, prompt: string | null, };
