// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateTaskTemplate = { project_id: string | null, title: string, description: string | null, template_name: string, };
