// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffChunkType } from "./DiffChunkType";

export type DiffChunk = { chunk_type: DiffChunkType, content: string, };
