// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DirectoryEntry } from "./DirectoryEntry";

export type DirectoryListResponse = { entries: Array<DirectoryEntry>, current_path: string, };
