// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DirectoryEntry = { name: string, path: string, is_directory: boolean, is_git_repo: boolean, };
