// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorType } from "./EditorType";

export type EditorConstants = { editor_types: Array<EditorType>, editor_labels: Array<string>, };
