// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorType } from "./EditorType";

export type EditorConfig = { editor_type: EditorType, custom_command: string | null, };
