// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EnvironmentInfo = { os_type: string, os_version: string, architecture: string, bitness: string, };
