// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutorConfig } from "./ExecutorConfig";

export type ExecutorConstants = { executor_types: Array<ExecutorConfig>, executor_labels: Array<string>, };
