// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffChunk } from "./DiffChunk";

export type FileDiff = { path: string, chunks: Array<DiffChunk>, };
