// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitBranch = { name: string, is_current: boolean, is_remote: boolean, last_commit_date: Date, };
