// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NormalizedEntryType } from "./NormalizedEntryType";

/**
 * Individual entry in a normalized conversation
 */
export type NormalizedEntry = { timestamp: string | null, entry_type: NormalizedEntryType, content: string, };
