// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutionProcessStatus } from "./ExecutionProcessStatus";
import type { ExecutionProcessType } from "./ExecutionProcessType";
import type { NormalizedConversation } from "./NormalizedConversation";

export type ProcessLogsResponse = { id: string, process_type: ExecutionProcessType, command: string, executor_type: string | null, status: ExecutionProcessStatus, normalized_conversation: NormalizedConversation, };
