// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchMatchType } from "./SearchMatchType";

export type SearchResult = { path: string, is_file: boolean, match_type: SearchMatchType, };
