// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SoundFile } from "./SoundFile";

export type SoundConstants = { sound_files: Array<SoundFile>, sound_labels: Array<string>, };
