// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateTaskTemplate = { title: string | null, description: string | null, template_name: string | null, };
