// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateExecutorSession = { session_id: string | null, prompt: string | null, summary: string | null, };
